modLoader="javafml" #mandatory
loaderVersion="[31,)" #mandatory (26 is current forge version)
issueTrackerURL="https://github.com/Alex-the-666/Citadel/issues" #optional
[[mods]] #mandatory
modId="citadel" #mandatory
version="1.1.8" #mandatory
displayName="Citadel" #mandatory
displayURL="https://github.com/Alex-the-666/Citadel" #optional
logoFile="citadel.png" #optional
credits="Gegy1000" #optional
authors="Alexthe666" #optional
# The description text for the mod (multi line!) (#mandatory)
description='''
A shared code library for many of Alexthe666's mods.
Code used from LLibrary with permission.
'''
[[dependencies.citadel]]
    modId="minecraft"
    mandatory=true
    versionRange="[1.15.2]"
    ordering="NONE"
    side="BOTH"
